version: '3.6'

services:

  notestoolapi:
    container_name: notestoolapi
    build:
        context: ./backend
        dockerfile: Dockerfile
    ports:
       - 3000:3000
    depends_on:
      - notestoolmongo

  notestoolmongo:
    image: mongo
    container_name: notestoolmongo
    restart: always
    volumes: 
      - ./mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: NotesTool
      MONGO_INITDB_ROOT_PASSWORD: looTsetoN

  notestoolmongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - notestoolmongo
    environment:
      ME_CONFIG_MONGODB_SERVER: notestoolmongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: NotesTool
      ME_CONFIG_MONGODB_ADMINPASSWORD: looTsetoN
