version: '3.6'

services:

  notestoolapi:
    container_name: notestoolapi
    build:
        context: ./backend
        dockerfile: Dockerfile
    ports:
       - 3000:3000
    depends_on:
      - notestoolmongo

  notestoolmongo:
    image: mongo
    container_name: notestoolmongo
    restart: always
    volumes: 
      - ./mongo_volume:/data/db
    env_file:
      - mongodb.env

  notestoolmongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - notestoolmongo
    env_file:
      - mongodb.env
    environment:
      ME_CONFIG_MONGODB_SERVER: notestoolmongo
